version: "3"
services:
  app-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dictionary
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - app-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://app-db:5432/dictionary
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update